### ISSUE TITLE
customize search style on FormBuilderSearchableDropdown

### ISSUE THREAD

**Issue by YouSour** [flutter-form-builder-ecosystem/form_builder_extra_fields#1]
hi , how can i customize search style on FormBuilderSearchableDropdown , i need to add hint text on search , i try to look through the document but i can't find anything about it , how can i do it ? thank in advance 😄 
![Simulator Screen Shot - iPhone 12 - 2022-01-13 at 11 37 49](https://user-images.githubusercontent.com/9318106/149267145-c99dbda5-9c39-45a4-ab50-7fe50f446c2c.png)

**Comment by deandreamatias** [comment]
@YouSour the solution work for you?
