### ISSUE TITLE
[FormBuilderTypeAhead] suggestion list is not adjusting

### ISSUE THREAD

**Issue by arnzuk** [flutter-form-builder-ecosystem/form_builder_extra_fields#13]
Hi,

Then type ahead field is focused and keyboard is visible, suggestion list gets wrong size  

![image](https://user-images.githubusercontent.com/6573428/162021972-2b2c59d0-2749-4f07-82d1-3b837223a02c.png)

How to scroll up more on field focus and give more space between field and keyboard?

Arnoldas

**Comment by deandreamatias** [comment]
This is a configuration of external dependency
Try take a look on this readme https://github.com/AbdulRahmanAlHamali/flutter_typeahead#customizing-the-suggestions-box
