### ISSUE TITLE
[FormFieldTouchSpin] still has mandatory focusNodes

### ISSUE THREAD

**Issue by rae-yoder** [flutter-form-builder-ecosystem/form_builder_extra_fields#15]
First off I really appreciate the quick turnaround to address the issues with the focus nodes. However there is still an ongoing issue where they have yet to be made optional or removed from `FormFieldTouchSpin` in `form_builder_extra_fields` I would appreciate a fix for this or at the very least a work-around for the time being. Appreciate all the work you have done building out this package.

**Comment by deandreamatias** [comment]
Hi,
Issues with FocusNode is solved by https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/pull/1045
Please, if this issue still happened, open a new bug issue
