### ISSUE TITLE
Searchable DropDownList with Network calls

### ISSUE THREAD

**Issue by Shiba-Kar** [flutter-form-builder-ecosystem/form_builder_extra_fields#18]
Is package could be used [searchable_dropdown](https://github.com/salim-lachdhaf/searchable_dropdown)

**Comment by deandreamatias** [comment]
This is implemented already https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/blob/04c07e9be926d42f7eb801abeeea3a64361a688a/example/lib/main.dart#L59
