### ISSUE TITLE
search field is missing in FormBuilderSearchableDropdown 

### ISSUE THREAD

**Issue by JohnGamal1** [flutter-form-builder-ecosystem/form_builder_extra_fields#27]
## Environment
Flutter 3.0.5

**Package version:**  
form_builder_extra_fields: ^8.3.0

<details>
  <summary>FormBuilderSearchableDropdown search is missing or I can't figure it </summary>
<details>
  <summary>Code sample</summary>

```
/ / ^8.3.0 code sample
FormBuilderSearchableDropdown<CustomerModel>(
                              name: "customerName",
                              initialValue: controller.orderModel.customer,
                              decoration: const InputDecoration(
                                border: OutlineInputBorder(),
                                hintText: "اختر اسم العميل",
                                labelText: "اسم العميل",
                              ),
                              compareFn: (item1, item2) =>
                                  item1.name == item2.name,
                              itemAsString: (item) => item.name,
                              onChanged: (c) {
                                controller.orderModel.customer =
                                    c ?? controller.orderModel.customer;
                                fbKey.currentState!
                                    .fields["customerPhoneNumber"]!
                                    .didChange(c);
                                fbKey.currentState!.fields["customerAddress"]!
                                    .didChange(c?.address);
                              },
                              items: List<CustomerModel>.from(
                                  _customer.customers.values),
                            ),
```

</details>

## Description
 I cannot find the search field FormBuilderSearchableDropdown as I used to in the 7.1.0 version as in this image
**Expected behavior:**
The search field in the 7.1.0 version
![image](https://user-images.githubusercontent.com/71144309/186532117-59a7d3c6-bc98-4d1a-8c97-cb53b0c9840b.png)

**Current behavior:**
The search field is missing
![image](https://user-images.githubusercontent.com/71144309/186532400-a91f8ff0-5473-4b93-9ead-ddca24a6de8e.png)

**Comment by deandreamatias** [comment]
If for some reason you set `popupProps`, need set property `showSearch: true`
With example code don't works too?

**Comment by JohnGamal1** [comment]
Yes it worked, thank you!
Can this be documented?

**Comment by deandreamatias** [comment]
Is documented in external package
