### ISSUE TITLE
[FormBuilderChipsInput] Exception: A FocusNode was used after being disposed

### ISSUE THREAD

**Issue by Draxent** [flutter-form-builder-ecosystem/form_builder_extra_fields#3]
I am using the code provided in the [example page](https://github.com/danvick/flutter_form_builder/blob/master/example/lib/main.dart).
When typing a new person in the **FormBuilderChipsInput**, then releasing the keyboard and then trying to write something else, I get the following error:

```
E/flutter (15302): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: A FocusNode was used after being disposed.
E/flutter (15302): Once you have called dispose() on a FocusNode, it can no longer be used.
E/flutter (15302): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> 
package:flutter/…/foundation/change_notifier.dart:106
E/flutter (15302): flutter-form-builder-ecosystem/flutter_form_builder#1      ChangeNotifier._debugAssertNotDisposed 
package:flutter/…/foundation/change_notifier.dart:112
E/flutter (15302): flutter-form-builder-ecosystem/flutter_form_builder#2      ChangeNotifier.notifyListeners 
package:flutter/…/foundation/change_notifier.dart:201
E/flutter (15302): flutter-form-builder-ecosystem/flutter_form_builder#3      FocusNode._notify 
package:flutter/…/widgets/focus_manager.dart:970
E/flutter (15302): flutter-form-builder-ecosystem/flutter_form_builder#4      FocusManager._applyFocusChange
```
As you can see from the image below, the suggestion is not showed when writing "pa".

![image](https://user-images.githubusercontent.com/4294247/84086017-2914f400-a9e7-11ea-81a0-913c6d22a9f8.png)

**Comment by deandreamatias** [comment]
Hi!
Please enter to [Discord server](https://discord.com/invite/25KNPMJQf2) (invitation link) and take a look on [this message](https://discord.com/channels/985922433578053673/994579381659914260/1078998449132937286)
Thanks

**Comment by deandreamatias** [comment]
This issue is solved by https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/pull/1045
