### ISSUE TITLE
[FormBuilderTypeAhead] Passed parameters are ignored

### ISSUE THREAD

**Issue by astubenbord** [flutter-form-builder-ecosystem/form_builder_extra_fields#36]
Some parameters, such as a TextEditingController are listed in the constructor, but never used. This is very confusing and these fields should either be removed or the default value should be overridden. This should be easy to fix, e.g.

Currently (e.g. in FormBuilderTypeAhead):
```
FormBuilderTypeAhead({
..., 
TextEditingController? controller,
});
...  
  Widget build() {
    return TypeAhead(
    ...,
    controller: state._typeAheadController, // controller is ignored here!
    ...
    );
  }
)

```
Fix by overriding field from state if non null value provided: 
```
controller: controller ?? state._typeAheadController, 
```

I haven't looked into other classes, but I assume it's similar there. The "dead" parameters should be identified and either removed or much more preferably used as intended by overriding the defaults. I can help with this, just let me know what you think! :)

**Comment by deandreamatias** [comment]
Hi!
Feel free to open a PR to fix this
Thanks

**Comment by deandreamatias** [comment]
The controller is set on State:

```dart
The controller is set on State:
  @override
  void initState() {
    super.initState();
    _typeAheadController = widget.controller ??
        TextEditingController(text: _getTextString(initialValue));
    // _typeAheadController.addListener(_handleControllerChanged);
  }
```
