### ISSUE TITLE
[FieldBuilderColorPicker] Allowing specific colors to be picked

### ISSUE THREAD

**Issue by dean-pearce** [flutter-form-builder-ecosystem/form_builder_extra_fields#42]
**What you'd like to happen:**
I want to make it such a way that, the user is only allowed to pick from 3 or 4 pre-defined color blocks

Something similar to the `ColorPickerType.blockPicker`, but only with the few colors of my choosing.

**Comment by deandreamatias** [comment]
Hi @dean-pearce!
I see that with option blockPicker, can add a property `availableColors`. I think that is this that you need.
If you can open a PR to include this, will be awesome. Thanks!
