### ISSUE TITLE
Why this package does not allow Type of items other than 'String'

### ISSUE THREAD

**Issue by aliahmad79** [flutter-form-builder-ecosystem/form_builder_extra_fields#46]
## Why this package does not allow Type of items other than 'String'

dropdown_search does allow using custom class as Type of item for the widget and this package does also have code for custom class but in constructor it is limit the type to only `String` is there any reason on the limit?

I want to use BlockEntity as type like this. syntax is correct but runtime assert is not allowing
```dart
FormBuilderSearchableDropdown<BlockEntity?>(
                        popupProps: const PopupProps.dialog(showSearchBox: true),
                        dropdownSearchDecoration: InputStyle(hint: 'Select Block'),
                        name: 'block_id',
                        items: blocks == null ? [] : blocks!,
                        itemAsString: (item) => item == null ? '' : item.name!,
                        decoration: const InputDecoration( labelText: 'Block'),
                         filterFn: (block, q) => block!.name!.toLowerCase().contains(q.toLowerCase()),
                      )
```

![image](https://user-images.githubusercontent.com/79683584/206724735-41e42934-aae1-49bb-9055-548a1342e250.png)

![image](https://user-images.githubusercontent.com/79683584/206724813-94cf03a5-b614-4e9e-b320-8c8587066503.png)

![image](https://user-images.githubusercontent.com/79683584/206725651-e8499654-d2ee-43a5-bac3-36de5900fda5.png)

**Comment by deandreamatias** [comment]
Please try add a function to property compareFn to avoid this assert warning

**Comment by Dubemtopsite** [comment]
Had same issue too

Is there any fix for this becuase I just have to convert my Array of object to a string of array

**Comment by aliahmad79** [comment]
@deandreamatias Thank You
