### ISSUE TITLE
Issue displaying hintText for FormBuilderSearchableDropdown

### ISSUE THREAD

**Issue by Dubemtopsite** [flutter-form-builder-ecosystem/form_builder_extra_fields#48]
Hi Guys,
I tried using the **FormBuilderSearchableDropdown** widget but am having issue displaying he **hintText** on the dropdown field

**My code**
![Screenshot from 2022-12-26 06-17-34](https://user-images.githubusercontent.com/31639636/209505316-115be213-758b-49e2-a8d5-d2e44b1e982d.png)

**This is outout below**
![image](https://user-images.githubusercontent.com/31639636/209505209-907e9069-247b-4dc7-bab2-0088526d93d0.png)

**Comment by deandreamatias** [comment]
Hi!
I tried reproduce this error with example code and I couldn't.
Maybe do you have a empty option in your items list?
[Screencast from 22-01-23 01:08:55.webm](https://user-images.githubusercontent.com/21011641/213894925-6de38bff-1f2b-4bec-b02d-afc5e199007c.webm)

**Comment by Dubemtopsite** [comment]
Okay thanks @deandreamatias will try out this solution from your code
