### ISSUE TITLE
[FormBuilderRatingBar] Cannot center align

### ISSUE THREAD

**Issue by EmmaJIfe** [flutter-form-builder-ecosystem/form_builder_extra_fields#52]
When using FormBuilderRatingBar I cannot get the rating icons to center align. I have used wrapAlignment: WrapAlignment.center, yet it does not seem to change anything. The parent of the FormBuilderRatingBar is a column which is also center aligned. Does anyone have any suggestions on what I should do?

**Comment by deandreamatias** [comment]
Please provider a example code and version of package that you used
