### ISSUE TITLE
[FormBuilderChipsInput] can not input through keyboard in web application

### ISSUE THREAD

**Issue by AscentionOne** [flutter-form-builder-ecosystem/form_builder_extra_fields#6]
Hi, @danvick  I run the example project on the web application in `form_builder_extra_fields 7.0.0`. However when I try to type in `FormBuilderChipsInput` field. It seems not getting the input from keyborad. Thanks!

**Comment by kirpit** [comment]
Unfortunately seems like the external package is not maintained anymore, people are looking for alternatives as even its own example is not working well anymore:
danvick/flutter_chips_input#97
danvick/flutter_chips_input#108

**Comment by deandreamatias** [comment]
Hi!
Please enter to [Discord server](https://discord.com/invite/25KNPMJQf2) (invitation link) and take a look on [this message](https://discord.com/channels/985922433578053673/994579381659914260/1078998449132937286)
Thanks

**Comment by deandreamatias** [comment]
This field is removed from package
