### ISSUE TITLE
[FormBuilderTypeAhead]: Add minCharsForSuggestions support

### ISSUE THREAD

**Issue by jbrechbuehl** [flutter-form-builder-ecosystem/form_builder_extra_fields#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

10.0.0

### What you'd like to happen

```Markdown
Hello :)

TypeAheadField already supports *minCharsForSuggestions*, I would like to have a *minCharsForSuggestions* parameter too in FormBuilderTypeAhead
```

**Comment by deandreamatias** [comment]
Solved in [this commit](https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/commit/f3b336d41dc4a4ae45b167f24b1f51e220435887)
