### ISSUE TITLE
FormBuilderSearchableDropdown height is not adjusting as per suggestions content

### ISSUE THREAD

**Issue by iamrohitsuthar** [flutter-form-builder-ecosystem/form_builder_extra_fields#8]
**FormBuilderSearchableDropdown** - Suggestions dropdown height is fixed and height is not shrinking even if I get only one or two suggestion items as a result after the search. 
But in **FormBuilderTypeAhead** list height is shrinking automatically based on the results.

 FormBuilderSearchableDropdown    | FormBuilderTypeAhead
:-------------------------:|:-------------------------:
 <img src="https://user-images.githubusercontent.com/37514288/148760536-b31ef593-f1ff-4698-ab14-ec7b4484dafa.png" width=380 height=320/>  |  <img src="https://user-images.githubusercontent.com/37514288/148760576-339fa31f-c8a7-4479-87d0-1ce76bbd60c0.png" width=400 height=280/>

**Comment by deandreamatias** [comment]
This is a config of external dependency. We need implement this config in field code to fit options.
Related: https://github.com/salim-lachdhaf/searchable_dropdown/issues/446

**Comment by deandreamatias** [comment]
You need config the `popupProps` like this: `popupProps: const PopupProps.menu(fit: FlexFit.loose)`
Related issue: https://github.com/salim-lachdhaf/searchable_dropdown/issues/446
